#!/bin/sh

[ -e tests.sh ] && . ./tests.sh || . ../tests.sh

NAME='Xtract mixed pe files'
FILE=../bins/pe/pemixed.exe
CMDS='!rabin2 -x ../bins/pe/pemixed.exe 2> /dev/null
rm -r pemixed.exe.fat
'
VERBOSE=1
IGNORE_ERR=1
EXPECT='pemixed.exe.fat/pemixed.exe.unknown_0.0 created (248)
pemixed.exe.fat/pemixed.exe.unknown_0.1 created (35328)
pemixed.exe.fat/pemixed.exe.unknown_0.2 created (35328)
'

run_test
rm -r pemixed.exe.fat
